name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Update NPM to v7
        run: |
          npm install -g npm@7
      - name: NPM install, lint and build
        run: |
          npm ci
          npm run lint
          npm run format
          npm run build:ci:all
      - name: Run tests
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test
